services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend-fe
    ports:
      - "5001:5000"

  frontend:
    build: ./notes-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./notes-fe/.env

volumes:
  db-data:
